[package]
name = "mpl_membership_token_indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
solana-client = "1.8.5"
solana-sdk = "1.8.5"
solana-transaction-status = "1.8.5"
parking_lot = "0.11.2"

[dependencies.indexer-core]
package = "mpl_membership_token_indexer_core"
version = "=0.1.0"
path = "../core"
